CREATE TABLE user_colors (
	id		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	user_id	INTEGER NOT NULL,
	color_id	INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(color_id) REFERENCES colors(id) ON UPDATE CASCADE ON DELETE CASCADE
);

